### ISSUE TITLE
Imagine api return 50035

### ISSUE THREAD

**Issue by foundVanting** [hongliang5316/midjourney-apiserver#1]
Call checkResponse failed, err: resp.StatusCode: 400, body: {"message": "Invalid Form Body", "code": 50035, "errors": {"data": {"_errors": [{"code": "INTERACTION_APPLICATION_COMMAND_INVALID_VERSION", "message": "This command is outdated, please try again in a few minutes"}]}}}

**Comment by foundVanting** [comment]
midjourney-go 包
version 改为 1166847114203123795就可以了，希望version 可以从外部传入

**Comment by hongliang5316** [comment]
> midjourney-go 包
> 
> version 改为 1166847114203123795就可以了，希望version 可以从外部传入

@foundVanting 你好，欢迎提交PR。

**Comment by 1998-BossLee** [comment]
请问如何能知道这个版本的来源？是否有文档可以参照，我找了discord的文档没有找到。1166847114203123795

**Comment by 1998-BossLee** [comment]
请问如何能知道这个版本的来源？是否有文档可以参照，我找了discord的文档没有找到。1166847114203123795 
@hongliang5316 @foundVanting

**Comment by hongliang5316** [comment]
@1998-BossLee

**Comment by hongliang5316** [comment]
@1998-BossLee 
你好, 需要抓包看下实际的报文内容, 可以看下我写的这篇文章: https://juejin.cn/post/7246924217681117244

**Comment by 1998-BossLee** [comment]
> @1998-BossLee 你好, 需要抓包看下实际的报文内容, 可以看下我写的这篇文章: https://juejin.cn/post/7246924217681117244

@hongliang5316  原来如此，已点赞，我有一个问题希望可以交流一下。version过期的时候请求会返回内容，如果version没有过期正常调用的话是没有返回值的，需要连接机器人监听消息。 
参数里有个once，表示一次唯一请求，后续再次使用同一个once不会生成绘画任务，并且请求也没有结果返回。违禁词亦是如此，那么如何知道当前本次绘画是否成功了呢？得从机器人消息监听里判断吗？

**Comment by hongliang5316** [comment]
@1998-BossLee 
绘画是异步的, 绘画的进度会通过回调的形式给到, 参考下这个示例: https://github.com/hongliang5316/midjourney-apiserver?tab=readme-ov-file#how-to-use
